/*
* generated by Xtext
*/
package org.sonatype.maven.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DependencyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/sonatype/maven/parser/antlr/internal/InternalDependencyDsl.tokens");
	}
}
